'use strict';
const bcrypt = require('bcryptjs');
const genPassword = async (password) => {
  return await bcrypt.hash(password, 12);
};

module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('users', [
      {
        first_name: 'Somchai',
        last_name: 'Boripat',
        email: 'sb@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1990/01/11',
        weight: '80',
        height: '190',
        role: 'Specialist',
        id_card_number: '1100119821239',
        address: '20 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Personal Trainer',
        description: 'I am a trainner who help you to enjoy excising',
        years_of_experience: new Date(
          Date.now() - 6 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Sommhai',
        last_name: 'Totrakul',
        email: 'st@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1995/05/11',
        weight: '76',
        height: '174',
        role: 'Specialist',
        id_card_number: '1100119821240',
        address: '21 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Personal Trainer',
        description: 'Trainer for everyone who want to burn fat',
        years_of_experience: new Date(
          Date.now() - 6 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Sombat',
        last_name: 'Methani',
        email: 'sm@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1987/04/21',
        weight: '80',
        height: '180',
        role: 'Specialist',
        id_card_number: '1100119821241',
        address: '21 Onnut Prakanong Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Personal Trainer',
        description: 'Trainner for lose weights',
        years_of_experience: new Date(
          Date.now() - 8 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Suchart',
        last_name: 'Ratakorn',
        email: 'sr@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1992/07/11',
        weight: '79',
        height: '178',
        role: 'Specialist',
        id_card_number: '1100119821242',
        address: '25 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Personal Trainer',
        description: 'Trainner for building muscle',
        years_of_experience: new Date(
          Date.now() - 8 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Somsri',
        last_name: 'Karuna',
        email: 'sk@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1996/08/14',
        weight: '50',
        height: '158',
        role: 'Specialist',
        id_card_number: '1100119821243',
        address: '25 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Nutritionist',
        description: 'Design food for elder',
        years_of_experience: new Date(
          Date.now() - 5 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Somsakul',
        last_name: 'Jaidee',
        email: 'sj@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1989/12/14',
        weight: '65',
        height: '165',
        role: 'Specialist',
        id_card_number: '1100119821244',
        address: '230 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Nutritionist',
        description: 'Design food for bodybuilders',
        years_of_experience: new Date(
          Date.now() - 7 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Somjai',
        last_name: 'Saisamon',
        email: 'ss@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1997/09/05',
        weight: '59',
        height: '155',
        role: 'Specialist',
        id_card_number: '1100119821245',
        address: '130 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Nutritionist',
        description: 'For people who want to lose weight in the right way',
        years_of_experience: new Date(
          Date.now() - 6 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Orapin',
        last_name: 'Jathawong',
        email: 'oj@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1989/04/05',
        weight: '59',
        height: '158',
        role: 'Specialist',
        id_card_number: '1100119821246',
        address: '10 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Physiotherapist',
        description: 'I am a physiotherapist with expertise in stretching',
        years_of_experience: new Date(
          Date.now() - 4 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Orn-anong',
        last_name: 'leelathawong',
        email: 'ol@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1984/04/05',
        weight: '61',
        height: '160',
        role: 'Specialist',
        id_card_number: '1100119821247',
        address: '10 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Physiotherapist',
        description:
          'I am a physiotherapist who takes care of the health of people who has an office syndrome',
        years_of_experience: new Date(
          Date.now() - 10 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Angkana',
        last_name: 'Wiwat',
        email: 'aw@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1990/02/24',
        weight: '54',
        height: '150',
        role: 'Specialist',
        id_card_number: '1100119821248',
        address: '100 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Physiotherapist',
        description:
          'I am a physiotherapist who takes care of the health of kids who age under 18 years old',
        years_of_experience: new Date(
          Date.now() - 3 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Angsumalin',
        last_name: 'Kanya',
        email: 'ak@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1991/06/05',
        weight: '59',
        height: '149',
        role: 'Specialist',
        id_card_number: '1100119821249',
        address: '14 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Physiotherapist',
        description: 'I am a physiotherapist who takes care of elder',
        years_of_experience: new Date(
          Date.now() - 12 * 365 * 24 * 60 * 60 * 1000
        ),
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Karagate',
        last_name: 'Kasuma',
        email: 'kk@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1993/08/28',
        weight: '53',
        height: '158',
        role: 'Specialist',
        id_card_number: '1100119821248',
        address: '10 Prachachuen Jatujak Bangkok 10110',
        health_coin: 0,
        application_status: 'Accepted',
        area: 'Physiotherapist',
        years_of_experience: new Date(
          Date.now() - 8 * 365 * 24 * 60 * 60 * 1000
        ),
        description:
          'I am a physiotherapist who takes care of the health of Thai national team athletes',
        created_at: new Date(),
        updated_at: new Date(),
      },
      //User : Customer
      {
        first_name: 'Somying',
        last_name: 'yooyen',
        email: 'sy@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1993/08/28',
        weight: '70',
        height: '160',
        role: 'Customer',

        health_coin: 0,
        goals: 'Back Pain',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Thanakit',
        last_name: 'yooyen',
        email: 'ty@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1994/09/18',
        weight: '76',
        height: '170',
        role: 'Customer',

        health_coin: 1,
        goals: 'Neck and Shoulder Ache',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Thanasuk',
        last_name: 'Tonklar',
        email: 'tt@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1993/10/18',
        weight: '86',
        height: '184',
        role: 'Customer',

        health_coin: 0,
        goals: 'Headache',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Thanawuth',
        last_name: 'Maneechan',
        email: 'tm@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1980/10/18',
        weight: '90',
        height: '180',
        role: 'Customer',

        health_coin: 2,
        goals: 'Lowerbody Pain',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Prayuth',
        last_name: 'Ngoongngoong',
        email: 'pn@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1970/10/18',
        weight: '80',
        height: '170',
        role: 'Customer',

        health_coin: 3,
        goals: 'After Surgery Recovery',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Prawith',
        last_name: 'Mairoo',
        email: 'pm@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1950/11/30',
        weight: '87',
        height: '176',
        role: 'Customer',

        health_coin: 2,
        goals: 'Burn Fat',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Anuthin',
        last_name: 'Noo',
        email: 'an@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1955/11/30',
        weight: '79',
        height: '173',
        role: 'Customer',

        health_coin: 3,
        goals: 'Ready to Play',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Taksin',
        last_name: 'Shinjung',
        email: 'ts@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Male',
        birth_date: '1951/11/30',
        weight: '74',
        height: '170',
        role: 'Customer',

        health_coin: 2,
        goals: 'Building Muscle',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        first_name: 'Yingluck',
        last_name: 'Kaikao',
        email: 'yk@gmail.com',
        google_id: '',
        password: await genPassword('123456'),
        gender: 'Female',
        birth_date: '1965/11/30',
        weight: '65',
        height: '158',
        role: 'Customer',

        health_coin: 0,
        goals: 'Just for Fun',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
